# Generated by Django 6.1.1 on 2026-09-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200)),
                ('tour_date', models.DateField()),
                ('customer_count', models.PositiveIntegerField(default=0)),
                ('collection', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hotel_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('car_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
