# Generated by Django 6.1.1 on 2026-09-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='package_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
